### PR TITLE
Support T4 plus multiple SPI busses

### PR DESCRIPTION
**Pull request by KurtE**
Using the update GFX to work with T4, this now builds and runs.  

Again This requires updates of the Adafruit_GFX library to work on T4.

Continue with T4 support - Wanted to get beyond just using SPI.transfer(), to update the display, so instead added support for SPI.beginTransaction/endTransaction, plus then code use their FIFO queue.

The code also supports using any IO pins for T4 and does the bitbang
SPI, which acutally may be faster.

While at it, also updated the T3.x code to use begin/endTransaction as well, plus hopefully be able to use other SPI busses (SPI1, SPI2)....

Currently removed Arduino AVR and DUE support.

Tested on T4 on SPI and SPI2 (don't have a setup for SPI1 yet)
On T3.6 tried on SPI and SPI1

Built it for T-LC

disable Serial debug outputs

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
Is this ready to merge?

**Comment by KurtE** [comment]
Sorry I was out yesterday… 

 

It could be ready anytime.  There are/were a few things I wanted to check out, but that can before/after

 

Things I was still looking at:

a.	What the default ROW/COL offsets are for when you use the initr(INITR_144GREENTAB).  In Adafruit library it is setup to default to the offsets needed for their product, whereas in ours currently setup to match the ones I have.  I now have one that matches Adafruit… So going to see if I accidentally changed it in this PR or was done a long time ago…  I did add another INITR_144GREENTAB_OFFSET, which currently matches the Adafruit board…. Thinking of swapping these.   But there is also now an API Lada Ada suggested to allow the user to set the row/col offset, which can also work to after using either tab color.
b.	I have ST7789 support in there, which is sub-class of ST7735 class.  Wondering if I should take an hour and do like Adafruit now does and convert all of the ST7735 class code to ST77XX class code and make both displays be sub-classes.  Only thing in subclasses are the init functions (including tables of init code) and setRotation.  
c.	Maybe update one or more example apps, to show how to do some of this stuff.   I already have the graphic test program showing how to do ST7789 (commented out tft object of the right class) and commented out init function.   But thinking of maybe adding my simple test program that allows you to see if the offsets are working properly.  

But if you are ready for new Beta build can pull in at any time.  The new code does have some good improvements over existing stuff.  Things like: T4 support, Support for all SPI busses, fixes for setRotation…

**Comment by KurtE** [comment]
Note: from my a) above looks like the INITR_144GREENTAB was changed from your current code so I will do the swap of the two... 

Should be done in the next hour (more or less)

**Comment by KurtE** [comment]
Fixed INITR_144GREENTAB to match older code.  Updated two examples (graphictest, rotationtest) that allow you to configure for ST7735 or ST7789, plus put in commented out call for setting the rowcol start position, which makes it work on two of my boards... And it works without call on my other one which matches the Adafruit on. Also tested on a 1.8" 128x160 and it is working as well... 

You are free to pull in PR now or if you prefer, I can squash many of these down into one change
(git rebase -i HEAD~8)

**Pull request merged**
